guilds:
- current_games_channels: []
  guild_id: 741435438807646268
  guild_name: Jacob's Server of Burgers
  upcoming_games_channels: []
  webhooks: []
max_webhooks: 12
replace_blacklist: []
replacement_timeout: 30
running_status_message: you
running_status_type: 3
startup_status_message: startup sequence
startup_status_type: 0
