guilds:
- announcement_channel: 1165434349664084058
  current_games_channel: 1165824736987726015
  guild_id: 741435438807646268
  guild_name: Jacob's Server of Burgers
  replacement_timeout: 30
  upcoming_games_channel: 1165824736987726015
  webhooks:
  - channel_id: 1165824736987726015
    webhook_id: 1174471725455511575
    webhook_url: https://discord.com/api/webhooks/1174471725455511575/eIv_8-yLUCyPmcyvi00vRqW2AbbDkTNouozlHu_xNniHC2XNOo_lohWa5IAAT_PBId6d
max_webhooks: 12
running_status_message: you
running_status_type: 3
startup_status_message: startup sequence
startup_status_type: 0
